// <auto-generated />
namespace RacingResource.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Progeny : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Progeny));
        
        string IMigrationMetadata.Id
        {
            get { return "201306061556126_Progeny"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
