// <auto-generated />
namespace RacingResource.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Add_UKHR_HorseID_And_Index : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_UKHR_HorseID_And_Index));
        
        string IMigrationMetadata.Id
        {
            get { return "201305291611360_Add_UKHR_HorseID_And_Index"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
