// <auto-generated />
namespace RacingResource.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Trainer : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Trainer));
        
        string IMigrationMetadata.Id
        {
            get { return "201305291734128_Trainer"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
