// <auto-generated />
namespace RacingResource.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class IsActiveAndAlternateNames : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IsActiveAndAlternateNames));
        
        string IMigrationMetadata.Id
        {
            get { return "201312181649533_IsActiveAndAlternateNames"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
