// <auto-generated />
namespace RacingResource.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class ResultId : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ResultId));
        
        string IMigrationMetadata.Id
        {
            get { return "201409161546507_ResultId"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
